# Generated by Django 2.2.8 on 2019-12-24 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_powerhour', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modified_powerhour', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerHourSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.URLField()),
                ('duration', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_powerhoursettings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modified_powerhoursettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PowerHourSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_powerhoursession', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modified_powerhoursession', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('power_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shotclock.PowerHour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='powerhour',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shotclock.PowerHourSettings'),
        ),
        migrations.CreateModel(
            name='MusicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_musicprofile', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modified_musicprofile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='music_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
