version: '2.1'

services:
  web:
    build: .
    command: ./run.sh
    ports:
      - '8000:8000'
    env_file: template.env
    environment:
      - CIRCLECI
    
  db:
    image: circleci/postgres
    ports:
      - '5432:5432'
    env_file: template.env
