version: '2.1'

services:
  web:
    build: .
    command: ./run.sh
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: 500k
        max-file: "1"    
    
  db:
    image: circleci/postgres
    ports:
      - '5432:5432'
    env_file: .env
