version: '2.1'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    env_file: .env
    
  db:
    image: circleci/postgres
    ports:
      - '5432:5432'
    env_file: .env
